### PR TITLE
Updated windows instructions

### PR DESCRIPTION
**Pull request by zment4**

### CODE REVIEW

**Comment by zment4** [comment]
Oh crud, I managed to mix this pull request up as well. Well, I'll fix it tomorrow to isolate it from the other one, and you can then choose whether you want to take it or not.

**Comment by zment4** [comment]
Alright, branch fixed to only hold the relevant changes.

**Comment by Xpl0itU** [comment]
WSL should be at least mentioned for windows and tell the user to follow the linux instructions if so

**Comment by zment4** [comment]
> WSL should be at least mentioned for windows and tell the user to follow the linux instructions if so

Agreed. Added a mention of it on the compiling instructions.

**Comment by jdah** [comment]
Windows instructions have been updated with 9fac3d2f61fd49ad25471d6b3838f4c61ae0bc6a :)

**Pull request closed without merging**
