### PR TITLE
Add info on how to run on windows

### PR DESCRIPTION
**Pull request by 39p**
I did not get audio working. Dont know why it doesn't work on windows QEMU or WSL

### CODE REVIEW

**Comment by zment4** [comment]
> I did not get audio working. Dont know why it doesn't work on windows QEMU or WSL

QEMU for Windows should be possible to get audio working with using the DSound driver and SB16 emulation. The GTK display doesn't work with SB16 emulation though, so you need to use the SDL display make SB16 emulation work. For instance: `qemu-system-i386 -display sdl -drive format=raw,file=boot.iso -audiodev id=dsound,driver=dsound -device sb16,audiodev=dsound`

**Comment by 39p** [comment]
> qemu-system-i386 -display sdl -drive format=raw,file=boot.iso -audiodev id=dsound,driver=dsound -device sb16,audiodev=dsound

Doesnt seem to work, just tried on the native QEMU builds that have SDL for windows. I don't think the ubuntu packages in WSL have SDL but I couldn't test

**Comment by zment4** [comment]
> > qemu-system-i386 -display sdl -drive format=raw,file=boot.iso -audiodev id=dsound,driver=dsound -device sb16,audiodev=dsound
> 
> Doesnt seem to work, just tried on the native QEMU builds that have SDL for windows. I don't think the ubuntu packages in WSL have SDL but I couldn't test

That uses dsound which is a Windows native sound driver. It only works in native Windows QEMU binaries, not through WSL. If you absolutely need to use WSL, you could try replacing dsound with sdl?

**Comment by 39p** [comment]
> EDIT2: Yup, just tested it. Downloaded the released boot.iso, installed native Windows QEMU binaries from https://qemu.weilnetz.de/w64/qemu-w64-setup-20210421.exe and ran with qemu-system-i386 -display sdl -drive format=raw,file=boot.iso -audiodev id=dsound,driver=dsound -device sb16,audiodev=dsound and both the game and sound work. Granted the audio is choppy, but it works. 🤔🤔🤔

Found out by installing the version you gave me it worked! I had a build from February 2021 for qemu and using the latest one seem to work. The audio is definitely choppy and bad. However this command seem to work fine.

> qemu-system-i386 -display sdl -drive format=raw,file=boot.iso -audiodev id=dsound,driver=dsound,out.fixed-settings=on,out.frequency=22050,out.buffer-length=80000,timer-period=100 -device sb16,audiodev=dsound

works fine. But sometimes when booting up the audio is just plain out choppy and sounds *very* bad like the first but just doing the command again seems to fix it. Weird.

**Comment by 39p** [comment]
https://github.com/jdah/tetris-os/commit/9fac3d2f61fd49ad25471d6b3838f4c61ae0bc6a adds info for windows so I will close this as it's not needed anymore

**Pull request closed without merging**
