### PR TITLE
Add the up arrow to rotate right

### PR DESCRIPTION
**Pull request by Drarig29**
I just added the up arrow to rotate and the tetrominos where spawning one cell too high to my liking.

You added the `-1` though, so there must be a reason... maybe for the end-game?

### CODE REVIEW

**Comment by Drarig29** [comment]
Oh, now I know why you did this 😅

image

**Comment by VFDan** [comment]
You should maybe remove that second change then.

**Comment by Drarig29** [comment]
Yes, but I would rather fix the detection of the end game. I think this is the actual problem here.

**Comment by Drarig29** [comment]
Okay, I removed the second change 😄

**Comment by jdah** [comment]
This is not necessary, you can already rotate right - thanks for the PR though.

**Comment by Drarig29** [comment]
I know it was possible but I always use the up arrow in Tetris games. Anyways.

**Pull request closed without merging**
